#!/bin/sh

# Run forge fmt on staged .sol files
staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.sol$')

if [ -n "$staged_files" ]; then
    echo "Running forge fmt..."
    forge fmt

    # Re-add formatted files
    echo "$staged_files" | xargs git add
fi

exit 0
